/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Español
 */
public class FormBanco extends javax.swing.JFrame {

    float acumulador = 0;
    int contador1 = 0;
    int contador2 = 0;
        
    
   
    /**
     * Creates new form FormBanco
     */
    public FormBanco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl1 = new javax.swing.JLabel();
        jl2 = new javax.swing.JLabel();
        jl3 = new javax.swing.JLabel();
        jl4 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        txt3 = new javax.swing.JTextField();
        btnDescontar = new javax.swing.JButton();
        jlTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl1.setText("Nombre :");
        getContentPane().add(jl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 39, 70, 30));

        jl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl2.setText("Monto :");
        getContentPane().add(jl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 103, 70, 30));

        jl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl3.setText("Debito :");
        getContentPane().add(jl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 198, 70, 30));

        jl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl4.setText("Total :");
        getContentPane().add(jl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 262, 70, 30));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 44, 278, -1));

        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 108, 101, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 80, -1));
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 203, 101, -1));

        btnDescontar.setText("Descontar");
        btnDescontar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescontarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDescontar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));
        getContentPane().add(jlTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 270, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/celda.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        float ingreso ;
        
        //ingreso = Integer.parseInt(this.txt2.getText());
        
        ingreso = Float.parseFloat(this.txt2.getText());

        acumulador += ingreso;
        contador1 ++;
        
        
        try {
            
        } catch ( NumberFormatException ex ) {
            .....aqui lo que quieras hacer si los campos estan vacios y tratan de calcular el total...
}
     
        if(txt2.getText().length()!=0){
            System.out.println("hay texto");
        } else {
            System.out.println("no hay texto");
        }
        
        if (contador1 + contador2 >= 10) {
            jlTotal.setText(acumulador+"/ Se ingreso 10 veces informaciòn");
            btnAgregar.setEnabled(false);
            btnAgregar.setEnabled(false);
        } else {
            jlTotal.setText(String.valueOf(acumulador));
            txt2.setText("");
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnDescontarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescontarActionPerformed
        // TODO add your handling code here:
        float descuento;
        descuento = Float.parseFloat(this.txt3.getText());
   
        acumulador -= descuento;
        contador2 ++ ;
        if (txt3.getText() == null) {
            jlTotal.setText("No se ingreso nada");
        }
        
        if (contador1 + contador2 >= 10) {
            jlTotal.setText(acumulador+"/ Se ingreso 10 veces informaciòn");
            btnAgregar.setEnabled(false);
            btnDescontar.setEnabled(false);
        } else {
            jlTotal.setText(String.valueOf(acumulador));
            txt3.setText("");
        }
    }//GEN-LAST:event_btnDescontarActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBanco().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnDescontar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jl1;
    private javax.swing.JLabel jl2;
    private javax.swing.JLabel jl3;
    private javax.swing.JLabel jl4;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    // End of variables declaration//GEN-END:variables
}
